os:
  - windows
  - linux
  - osx
language: node_js
node_js:
  - "node"
  - "10"
  - "8"
  - "6"
cache: yarn
before_install:
  yarn config set ignore-engines true
# fix running yarn installation on windows
env:
  - YARN_GPG=no
